'use strict';

// User-added players: turns a four-field spec (first name, last name,
// position, CFB overall) into a row shaped exactly like one extractLeavingPlayers
// produces, so the rest of the pipeline never learns these players are special.
//
// WHY A DONOR RATHER THAN SYNTHESIS. A departed row carries ~55 individual
// ratings plus height, weight, age, body type, archetype, head asset, career
// stats and an awards score. Inventing all of that from one overall number
// would mean encoding, per position, what a 78-overall corner's ratings look
// like -- a large tuning surface that would immediately drift from whatever
// the actual games do. Instead this borrows the whole row from the closest
// same-position player already in the pool and overwrites the four fields the
// user specified. Position shape, body, and archetype are then real values
// from a real player at that position, in this user's own dynasty.
//
// It is the same posture the app already takes twice elsewhere: the draft-class
// exporter gives a generated player a position-matched donor's gear and (for
// M27) its ability block, and lib/carousel/appearance.js borrows a donor blob
// for apparel. Nothing here invents an asset or a rating profile that the
// source data doesn't already contain.
//
// WHAT THIS DELIBERATELY DOES NOT DO. It does not place the player at a
// chosen draft slot, and it does not bypass rating conversion. The row goes
// into the pool as an ordinary prospect and is scored, ranked, converted and
// dev-traited by the same code as everyone else -- so a custom player lands
// where their talent actually puts them. That is a design choice, not an
// oversight: an entered overall is a COLLEGE overall, and every engine
// converts college ratings downward, so the Madden result is LOWER than the
// number typed in.
//
// That gap is surfaced, but not by predicting it. This app deliberately does
// not estimate a Madden overall (see the rating-engine direction note: Madden
// recomputes OVR in-game, and forcing a number here would be guessing at the
// game's own formula). Instead the custom player is flagged on the generated
// row -- `IsCustomPlayer` survives into the results table -- so the UI can
// point at where they actually landed and what their ratings actually became
// after conversion. Real output beats a predicted one, and it costs nothing:
// the class has already been generated by the time anyone looks.

const { POSITIONS } = require('./defaults');

// Matches lib/saveIO.js's own ratingFields derivation (int attributes whose
// name ends in "Rating"). Kept as a predicate rather than a hardcoded list so
// a schema change that adds a rating needs no edit here.
const isRatingField = (k) => /Rating$/.test(k) && k !== 'OverallRating';

const MIN_OVERALL = 1;
const MAX_OVERALL = 99;
// Long enough for any real name; the exporter truncates per-slot anyway (see
// setNameSafe in draftClassExporter.js). This exists to reject paste
// accidents, not to enforce the file format.
const MAX_NAME = 40;

// Ratings at or above this keep their shape when the row is shifted to a new
// overall; anything below it is left exactly as the donor had it. Same floor,
// for the same reason, as the one in diceRoll.js's applyDelta: a rating the
// position doesn't use (a receiver's throw accuracy sitting at 20) carries no
// information about how good the player is, and dragging it upward with the
// overall would quietly turn a specialist into an athlete at everything.
const SHIFT_FLOOR = 50;

function fail(msg) {
  const e = new Error(msg);
  e.userFacing = true;
  throw e;
}

// Validates and canonicalizes one user-entered spec. Throws with a message
// meant to be shown verbatim -- every branch names the field and what is
// wrong with it, because these are typed by hand in a form.
function normalizeCustomPlayer(spec, { index } = {}) {
  const where = Number.isInteger(index) ? ` (player ${index + 1})` : '';
  if (!spec || typeof spec !== 'object') fail(`Custom player${where} is not filled in.`);

  const firstName = String(spec.firstName ?? '').trim();
  const lastName = String(spec.lastName ?? '').trim();
  if (!firstName) fail(`Custom player${where} needs a first name.`);
  if (!lastName) fail(`Custom player${where} needs a last name.`);
  if (firstName.length > MAX_NAME || lastName.length > MAX_NAME) {
    fail(`Custom player${where} has a name longer than ${MAX_NAME} characters.`);
  }

  const position = String(spec.position ?? '').trim().toUpperCase();
  if (!POSITIONS.includes(position)) {
    fail(`Custom player${where} has an unknown position "${spec.position}". `
      + `Use one of: ${POSITIONS.join(', ')}.`);
  }

  const overall = Number(spec.overall);
  if (!Number.isFinite(overall) || overall < MIN_OVERALL || overall > MAX_OVERALL) {
    fail(`Custom player${where} needs a college overall between ${MIN_OVERALL} and ${MAX_OVERALL} `
      + `(got "${spec.overall}").`);
  }

  return { firstName, lastName, position, overall: Math.round(overall) };
}

// The pool row whose ratings this custom player borrows: same position,
// closest overall. Ties break on name so the same spec against the same pool
// always picks the same donor -- generation is seeded and reproducible
// everywhere else, and a donor chosen by array order would quietly break that
// the moment the pool's order changed.
//
// Returns null when the pool has nobody at that position at all, which is a
// real case in a small dynasty (no long snapper declared this year).
function pickDonor(pool, position, overall) {
  let best = null;
  let bestKey = null;
  for (const row of pool || []) {
    if (!row || String(row.Position) !== position) continue;
    const ovr = Number(row.OverallRating);
    if (!Number.isFinite(ovr)) continue;
    const key = [
      Math.abs(ovr - overall),
      String(row.LastName ?? ''),
      String(row.FirstName ?? ''),
      Number(row.rowIndex ?? 0),
    ];
    if (!best || compareKey(key, bestKey) < 0) { best = row; bestKey = key; }
  }
  return best;
}

function compareKey(a, b) {
  for (let i = 0; i < a.length; i++) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return 0;
}

const clampRating = (v) => Math.max(1, Math.min(99, Math.round(v)));

// Builds the pool row. `index` only disambiguates the synthetic rowIndex when
// several custom players are added at once.
function buildCustomRow(spec, pool, { index = 0 } = {}) {
  const s = normalizeCustomPlayer(spec, { index });
  const donor = pickDonor(pool, s.position, s.overall);
  if (!donor) {
    fail(`No ${s.position} in this dynasty's departing pool to base "${s.firstName} ${s.lastName}" on. `
      + `Custom players copy their body and rating shape from a real player at the same position, `
      + `so at least one ${s.position} has to be leaving. Pick another position, or load a save that has one.`);
  }

  // Shallow clone is enough: every field this overwrites is a scalar. The one
  // object-valued field (CareerStats) is deliberately SHARED with the donor
  // rather than deep-copied -- nothing downstream mutates it, and copying it
  // would only hide that the production numbers are borrowed.
  const row = { ...donor };

  const donorOverall = Number(donor.OverallRating);
  const delta = s.overall - donorOverall;
  if (delta !== 0) {
    for (const key of Object.keys(row)) {
      if (!isRatingField(key)) continue;
      const v = Number(row[key]);
      if (!Number.isFinite(v) || v < SHIFT_FLOOR) continue;
      row[key] = clampRating(v + delta);
    }
  }

  row.FirstName = s.firstName;
  row.LastName = s.lastName;
  row.Position = s.position;
  row.OverallRating = s.overall;

  // Identity. rowIndex is how Rosetta keys a player back to its save row;
  // a custom player has no save row, so it gets a namespaced value that can
  // never collide with a real index (which is a non-negative integer).
  row.rowIndex = `custom:${index}`;
  row.IsCustomPlayer = true;
  row.CustomDonor = `${donor.FirstName} ${donor.LastName} (${donor.Position} ${donorOverall})`;

  return row;
}

// Returns a NEW pool with the custom players appended.
//
// Never mutates `pool`. main.js holds the extracted pool in a module-level
// cache and reuses it for every generation, so appending in place would make
// each run stack another copy of the custom players onto the last run's --
// a duplicate per generation, growing silently. The test suite pins this.
function withCustomPlayers(pool, specs, log = () => {}) {
  const list = Array.isArray(specs) ? specs.filter(Boolean) : [];
  if (!list.length) return Array.isArray(pool) ? pool : [];

  const base = Array.isArray(pool) ? pool : [];
  const rows = list.map((spec, i) => buildCustomRow(spec, base, { index: i }));
  for (const r of rows) {
    log(`  custom player added: ${r.FirstName} ${r.LastName} (${r.Position}, college ${r.OverallRating}) `
      + `-- rating shape from ${r.CustomDonor}`);
  }

  // The pool array carries Rosetta lifecycle metadata as own properties (see
  // Rosetta.tagStage). A bare concat would drop it, and callers read
  // `pool.source`. Copy those across explicitly.
  const out = base.concat(rows);
  for (const key of Object.keys(base)) {
    if (/^\d+$/.test(key) || key === 'length') continue;
    try { out[key] = base[key]; } catch (e) { /* non-writable, skip */ }
  }
  return out;
}

module.exports = {
  POSITIONS,
  MIN_OVERALL,
  MAX_OVERALL,
  MAX_NAME,
  SHIFT_FLOOR,
  isRatingField,
  normalizeCustomPlayer,
  pickDonor,
  buildCustomRow,
  withCustomPlayers,
};
