// Phase 5c face-flag confirmation (FACES_AND_DRAFT_ROADMAP.md, Phase 5). NOT shipped.
//
// We found the face gate: the 16-bit face/portrait ID at binary offset 146-147.
// Faced template players cluster ~3700-4100 (byte 147 = 13-16); faceless ones
// ~15800-15925 (byte 147 = 61-62). Boireau (faceless) and Johnson (faced) share
// the same genericHeadName but differ ONLY in this field -> it, not the JSON
// head, gates whether a generic face renders.
//
// This runs isolated experiments on known-faceless players so ONE import answers
// two questions:
//   (1) Does moving the face-ID into the "faced" band make them render?
//   (2) Does genericHeadName still drive the LOOK (needed to hit "close to the
//       CFB autogenerated face")? -- one player gets its face-ID fixed AND its
//       head skin digit changed; if the rendered skin follows the head, the head
//       drives the look.
// All edits are same-length (fixed-struct byte writes + same-length JSON), so it
// stays in the 5b-validated path. Controls are left untouched.
//
// Usage: node tools/phase5cFlagTest.js
// Then import CAREERDRAFT-flagtest and report which listed ranks now show a face.

const fs = require('fs');
const path = require('path');
const os = require('os');
const {
  serializeDraftClassFile, setBinaryBytes, setFaceId, getFaceId, setJsonFieldSameLength,
} = require('../lib/draftClassFile');
const { loadTemplateModel } = require('../lib/draftClassTemplate');

function main() {
  const model = loadTemplateModel();
  const facedRef = getFaceId(model.players[4]); // Jericho Johnson, a known-faced player
  const legend = [];

  // Exp A (idx0 Fasusi): set ONLY byte 147 = 15 (keeps low byte). Cheapest possible flip.
  {
    const before = getFaceId(model.players[0]);
    model.players[0] = setBinaryBytes(model.players[0], [{ offset: 147, value: 15 }]);
    legend.push({ rank: 1, name: 'Fasusi', exp: `byte147 -> 15 (faceId ${before} -> ${getFaceId(model.players[0])}), head kept` });
  }
  // Exp B (idx1 Sanders): set ONLY byte 147 = 14.
  {
    const before = getFaceId(model.players[1]);
    model.players[1] = setBinaryBytes(model.players[1], [{ offset: 147, value: 14 }]);
    legend.push({ rank: 2, name: 'Sanders', exp: `byte147 -> 14 (faceId ${before} -> ${getFaceId(model.players[1])}), head kept` });
  }
  // Exp C (idx2 Griffin): fix face-ID into faced band AND change head skin 7->1.
  // If it renders and looks light-skinned, genericHeadName drives the look.
  {
    const head = model.players[2].json.visuals.genericHeadName; // gen_7_BMH_MG_020
    const newHead = head.replace(/^gen_\d/, 'gen_1');            // same length, skin 7 -> 1
    model.players[2] = setFaceId(model.players[2], facedRef);
    model.players[2] = setJsonFieldSameLength(model.players[2], 'genericHeadName', newHead);
    model.players[2] = setJsonFieldSameLength(model.players[2], 'skinTone', 1);
    legend.push({ rank: 3, name: 'Griffin', exp: `faceId -> ${facedRef} (faced), head ${head} -> ${newHead} (skin 7->1)` });
  }
  // Exp D (idx3 Boireau): copy the whole faced face-ID from Johnson.
  {
    const before = getFaceId(model.players[3]);
    model.players[3] = setFaceId(model.players[3], facedRef);
    legend.push({ rank: 4, name: 'Boireau', exp: `faceId ${before} -> ${facedRef} (copied from faced Johnson), head kept` });
  }
  // Controls: idx5 Carr (rank 6) and idx8 Beau Johnson (rank 9) left UNCHANGED.

  const buf = serializeDraftClassFile(model);
  const outDir = fs.existsSync(path.join(os.homedir(), 'Desktop')) ? path.join(os.homedir(), 'Desktop') : os.tmpdir();
  const outputPath = path.join(outDir, 'CAREERDRAFT-flagtest');
  fs.writeFileSync(outputPath, buf);

  console.log(`Wrote ${outputPath} (${buf.length} bytes).`);
  console.log('\nImport and report which of these now show a FACE:');
  for (const l of legend) console.log(`  Rank ${l.rank}  ${l.name.padEnd(9)} ${l.exp}`);
  console.log('  Rank 6  Carr      UNCHANGED control (should stay faceless)');
  console.log('  Rank 9  B.Johnson UNCHANGED control (should stay faceless)');
  console.log('\nWhat we learn:');
  console.log('  - Ranks 1-4 now render a face -> offset 146-147 face-ID is the gate. Our exporter');
  console.log('    sets it into the faced band and every written CFB player gets a face.');
  console.log('  - Rank 3 specifically: if it renders LIGHT-skinned, genericHeadName drives the look,');
  console.log('    so writing the CFB player\'s head+skin gets us "close to the CFB autogenerated face".');
}

main();
